development:
  password: bdeab93dddcc2c82e5963a3ead517330
  theme_id: "14385184823"
  store: the-smoke-trend.myshopify.com
production:
  password: 97307e15a17231212ecf37c41f6969f3
  theme_id: "14491680823"
  store: the-smoke-trend.myshopify.com
  timeout: 60s

